version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
